# ────────────────────────────────────────────────────────────────
# NexArena — Dockerfile for Google Cloud Run
# ────────────────────────────────────────────────────────────────
# Multi-stage build keeps the final image lean:
#   1. deps   — install production + dev dependencies
#   2. builder — compile the Next.js app
#   3. runner  — minimal production image (~150 MB vs ~800 MB)
# ────────────────────────────────────────────────────────────────

# ── Stage 1: Install dependencies ────────────────────────────────
FROM node:20-alpine AS deps

# Install libc compat for native modules on Alpine
RUN apk add --no-cache libc6-compat

WORKDIR /app

# Copy only package manifests first — this layer is cached unless
# package.json or package-lock.json changes.
COPY package.json package-lock.json ./

# Use ci for reproducible installs (respects package-lock.json exactly)
RUN npm ci

# ── Stage 2: Build the Next.js app ───────────────────────────────
FROM node:20-alpine AS builder

WORKDIR /app

# Copy installed node_modules from deps stage
COPY --from=deps /app/node_modules ./node_modules

# Copy all source files
COPY . .

# Build-time env vars (non-secret public config).
# Secret values (GEMINI_API_KEY, Firebase keys) must be injected
# at runtime via Cloud Run environment variables — never baked in.
ENV NEXT_TELEMETRY_DISABLED=1
ENV NODE_ENV=production

# Produce the optimised production build
RUN npm run build

# ── Stage 3: Production runner ────────────────────────────────────
FROM node:20-alpine AS runner

WORKDIR /app

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1

# Cloud Run injects PORT; Next.js respects it natively.
ENV PORT=8080
EXPOSE 8080

# Create a non-root user for security best practice
RUN addgroup --system --gid 1001 nodejs && \
    adduser  --system --uid 1001 nextjs

# Copy only what's needed to run the app:
#   - public assets
#   - standalone server output (generated by Next.js standalone mode)
#   - static build artefacts
COPY --from=builder /app/public ./public
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

USER nextjs

# Cloud Run health check listens on $PORT
# Next.js standalone server.js honours the PORT env var automatically
CMD ["node", "server.js"]
